{{- if .Values.secrets.slurmAuth.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm-exporter.slurmAuthSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "slurm-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets.slurmAuth.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

{{- if .Values.secrets.tls.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm-exporter.tlsSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "slurm-exporter.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- with .Values.secrets.tls.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

{{- if .Values.secrets.basicAuth.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm-exporter.basicAuthSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "slurm-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets.basicAuth.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}