apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: slurm-staging

resources:
- ../../

patchesStrategicMerge:
- deployment-staging.yaml

images:
- name: slurm-exporter
  newTag: staging-latest

replicas:
- name: slurm-exporter
  count: 1

commonLabels:
  environment: staging

patches:
- target:
    kind: Deployment
    name: slurm-exporter
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0/configMap/name
      value: slurm-exporter-config-staging